version: 2
jobs:
  build:  
    docker:
      - image: circleci/node:15
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm uninstall graphql
      - run: npm install express express-graphql
      - run: npm install graphql

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/lab4
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ${DOCKER_LOGIN}/lab4
          tag: latest
  
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: 
          name: Connect and deploy through SSH
          no_output_timeout: 30s
          command: ssh -o "StrictHostKeyChecking no" ec2-user@${AWS_DOMAIN} "
              sudo service docker start;
              bash script.sh;"